baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Baked | Creative Agency | Independent Creative Studio"

[params]
description = "Baked is an independent creative studio working with some of the world’s biggest brands. We’re specialists in world-class content production, 3D animation and creative design."
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]